name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: KyleGospo/metrics@0fee81a4d788cc2043732714563f21314ce4dd5f # master
        with:
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://universal-blue.org/
